apiVersion: v2
name: genai-pgvector
description: PostgreSQL with pgvector extension for vector embeddings
type: application
version: 0.1.0
appVersion: "16"

dependencies:
  - name: postgresql
    version: "18.5.6"
    repository: "https://charts.bitnami.com/bitnami"
