minio:
  persistence:
    storageClass: local-path
    size: 5Gi
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio-console.platform.127.0.0.1.nip.io
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio.platform.127.0.0.1.nip.io
