datahub:
  datahub-frontend:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: datahub.genai.127.0.0.1.nip.io
          paths:
            - /

  datahub-gms:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: datahub-gms.genai.127.0.0.1.nip.io
          paths:
            - /
