{{- if not .Values.existingRootPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-ce.fullname" . }}-initial-password
  labels:
    {{- include "gitlab-ce.labels" . | nindent 4 }}
type: Opaque
stringData:
  initial_root_password: {{ .Values.initialRootPassword | quote }}
{{- end }}
