apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-litellm-config
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: genai-mlops
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
