{{- if or .Values.secrets.n8nApiKey .Values.secrets.litellmApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  {{- if .Values.secrets.n8nApiKey }}
  n8n-api-key: {{ .Values.secrets.n8nApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.litellmApiKey }}
  litellm-api-key: {{ .Values.secrets.litellmApiKey | quote }}
  {{- end }}
{{- end }}
