apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: metamcp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: genai-mlops
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 12009
      targetPort: 12009
      protocol: TCP
      name: backend
  selector:
    app.kubernetes.io/name: metamcp
    app.kubernetes.io/instance: {{ .Release.Name }}
