apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genai-odd-platform.fullname" . }}
  labels:
    {{- include "genai-odd-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "genai-odd-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "genai-odd-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: odd-platform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.config.spring.datasource.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.config.spring.datasource.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: password
            - name: AUTH_TYPE
              value: {{ .Values.config.auth.type | quote }}
            - name: SESSION_PROVIDER
              value: {{ .Values.config.session.provider | quote }}
            - name: METRICS_STORAGE
              value: {{ .Values.config.metrics.storage | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
