apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: mcp-gitlab
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: genai-mlops
type: Opaque
stringData:
  gitlab-token: {{ .Values.gitlab.token | quote }}
