apiVersion: v1
kind: Service
metadata:
  name: genai-mcp-datahub
  labels:
    app.kubernetes.io/name: mcp-datahub
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: mcp-datahub
