apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: mcp-kubernetes
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: genai-mlops
