apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-runner.fullname" . }}-config
  labels:
    {{- include "gitlab-runner.labels" . | nindent 4 }}
data:
  config.toml: |
    concurrent = {{ .Values.runner.concurrent }}
    check_interval = 3
    shutdown_timeout = 30

    [[runners]]
      name = "{{ include "gitlab-runner.fullname" . }}"
      url = "{{ .Values.gitlabUrl }}"
      executor = "kubernetes"
      environment = ["FF_USE_INIT_WITH_DOCKER_EXECUTOR=true"]

      [runners.kubernetes]
        namespace = "{{ .Values.runner.jobNamespace }}"
        image = "{{ .Values.runner.defaultImage }}"
        pull_policy = ["{{ .Values.runner.pullPolicy }}"]
        service_account = "{{ include "gitlab-runner.fullname" . }}-job"
