#!/usr/bin/env bash
# Setup n8n owner account and API key for programmatic access.
# Usage: ./scripts/setup-n8n-api.sh [--force]
#
# Requires: n8n running at localhost:5678, python3
# Idempotent — skips if secrets/n8n_api_key already exists (unless --force).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_DIR="$REPO_DIR/secrets"
FORCE="${1:-}"
N8N_URL="${N8N_URL:-http://localhost:5678}"
N8N_OWNER_EMAIL="${N8N_OWNER_EMAIL:-admin@genai-mlops.local}"
# Read password from secrets file (generated by init-secrets.sh)
if [ -f "$SECRETS_DIR/n8n_owner_password" ]; then
    N8N_OWNER_PASSWORD="${N8N_OWNER_PASSWORD:-$(cat "$SECRETS_DIR/n8n_owner_password")}"
else
    echo "  ✗ Missing secrets/n8n_owner_password — run: bash scripts/init-secrets.sh"
    exit 1
fi
N8N_OWNER_FIRST="${N8N_OWNER_FIRST:-Admin}"
N8N_OWNER_LAST="${N8N_OWNER_LAST:-User}"

# ── Pre-checks ────────────────────────────────────────────────────────────────

if [ -f "$SECRETS_DIR/n8n_api_key" ] && [ "$FORCE" != "--force" ]; then
    echo "  ✓ n8n_api_key already exists (use --force to regenerate)"
    exit 0
fi

echo "Setting up n8n API access..."

# Wait for n8n to be healthy
echo -n "  Waiting for n8n at $N8N_URL..."
for i in $(seq 1 30); do
    if curl -sf "$N8N_URL/healthz" >/dev/null 2>&1; then
        echo " ready"
        break
    fi
    if [ "$i" = "30" ]; then
        echo " TIMEOUT"
        echo "  ✗ n8n not responding at $N8N_URL/healthz after 30s"
        exit 1
    fi
    echo -n "."
    sleep 1
done

# ── All auth handled in one Python script to avoid cookie/shell issues ────────

API_KEY=$(python3 - "$N8N_URL" "$N8N_OWNER_EMAIL" "$N8N_OWNER_PASSWORD" "$N8N_OWNER_FIRST" "$N8N_OWNER_LAST" << 'PYEOF'
import urllib.request, urllib.error, json, time, sys, re

N8N_URL = sys.argv[1]
EMAIL = sys.argv[2]
PASSWORD = sys.argv[3]
FIRST = sys.argv[4]
LAST = sys.argv[5]

def post(url, data, headers=None):
    hdrs = {"Content-Type": "application/json"}
    if headers:
        hdrs.update(headers)
    req = urllib.request.Request(url, json.dumps(data).encode(), hdrs)
    try:
        resp = urllib.request.urlopen(req)
        return resp.status, json.loads(resp.read()), dict(resp.headers)
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        try:
            return e.code, json.loads(body), {}
        except json.JSONDecodeError:
            return e.code, {"raw": body}, {}

def get(url, headers=None):
    req = urllib.request.Request(url, headers=headers or {})
    try:
        resp = urllib.request.urlopen(req)
        return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read().decode())

# 1. Create owner (may already exist)
print("  Creating owner account...", file=sys.stderr)
code, resp, hdrs = post(f"{N8N_URL}/rest/owner/setup", {
    "email": EMAIL,
    "password": PASSWORD,
    "firstName": FIRST,
    "lastName": LAST
})

auth_cookie = None
if code == 200 and "id" in resp.get("data", resp):
    print(f"  ✓ Owner account created ({EMAIL})", file=sys.stderr)
    # Extract cookie from setup response
    sc = hdrs.get("Set-Cookie", hdrs.get("set-cookie", ""))
    m = re.search(r'n8n-auth=([^;]+)', sc)
    if m:
        auth_cookie = m.group(1)
else:
    print("  ⚠ Owner may already exist, attempting login...", file=sys.stderr)

# 2. Login if we don't have a cookie yet
if not auth_cookie:
    req = urllib.request.Request(
        f"{N8N_URL}/rest/login",
        json.dumps({
            "emailOrLdapLoginId": EMAIL,
            "password": PASSWORD,
            "mfaToken": "",
            "mfaRecoveryCode": ""
        }).encode(),
        {"Content-Type": "application/json"}
    )
    try:
        resp = urllib.request.urlopen(req)
        sc = resp.headers.get("Set-Cookie", "")
        m = re.search(r'n8n-auth=([^;]+)', sc)
        if m:
            auth_cookie = m.group(1)
            print(f"  ✓ Logged in as {EMAIL}", file=sys.stderr)
        else:
            print("  ✗ No auth cookie in login response", file=sys.stderr)
            sys.exit(1)
    except urllib.error.HTTPError as e:
        print(f"  ✗ Login failed: {e.code} {e.read().decode()}", file=sys.stderr)
        sys.exit(1)

# 3. Delete existing API keys (for --force)
code, existing = get(f"{N8N_URL}/rest/api-keys", {"Cookie": f"n8n-auth={auth_cookie}"})
if code == 200:
    keys = existing.get("data", existing) if isinstance(existing, dict) else existing
    if isinstance(keys, list):
        for key in keys:
            kid = key.get("id", "")
            if kid:
                dreq = urllib.request.Request(
                    f"{N8N_URL}/rest/api-keys/{kid}",
                    method="DELETE",
                    headers={"Cookie": f"n8n-auth={auth_cookie}"}
                )
                try:
                    urllib.request.urlopen(dreq)
                    print(f"  → Deleted existing API key {kid}", file=sys.stderr)
                except urllib.error.HTTPError:
                    pass

# 4. Create new API key
expires_at = int((time.time() + 365 * 24 * 3600) * 1000)
req = urllib.request.Request(
    f"{N8N_URL}/rest/api-keys",
    json.dumps({
        "label": "genai-mlops-api",
        "scopes": ["workflow:list"],
        "expiresAt": expires_at
    }).encode(),
    {
        "Content-Type": "application/json",
        "Cookie": f"n8n-auth={auth_cookie}"
    }
)
try:
    resp = urllib.request.urlopen(req)
    result = json.loads(resp.read())
    data = result.get("data", result)
    raw_key = data.get("rawApiKey", data.get("apiKey", ""))
    if not raw_key or raw_key.startswith("***"):
        print("  ✗ No raw API key in response", file=sys.stderr)
        sys.exit(1)
    print(f"  ✓ API key created", file=sys.stderr)
    # Print ONLY the key to stdout
    print(raw_key)
except urllib.error.HTTPError as e:
    print(f"  ✗ API key creation failed: {e.code} {e.read().decode()}", file=sys.stderr)
    sys.exit(1)
PYEOF
)

# The Python script prints status to stderr, key to stdout
# $API_KEY now holds just the raw key

if [ -z "$API_KEY" ] || [ "$API_KEY" = "None" ]; then
    echo "  ✗ Empty API key returned"
    exit 1
fi

mkdir -p "$SECRETS_DIR"
printf '%s' "$API_KEY" > "$SECRETS_DIR/n8n_api_key"
chmod 600 "$SECRETS_DIR/n8n_api_key"

echo "  ✓ API key saved to secrets/n8n_api_key"

# ── Verify ────────────────────────────────────────────────────────────────────

VERIFY=$(curl -sf "$N8N_URL/api/v1/workflows" \
    -H "X-N8N-API-KEY: $API_KEY" 2>&1) || true

if echo "$VERIFY" | grep -q '"data"'; then
    COUNT=$(echo "$VERIFY" | python3 -c "import sys,json; print(len(json.loads(sys.stdin.read()).get('data',[])))" 2>/dev/null || echo "?")
    echo "  ✓ API key verified ($COUNT workflows accessible)"
else
    echo "  ⚠ API key saved but verification failed — n8n may need restart"
fi

echo ""
echo "Done. n8n API access configured."
echo "  Owner: $N8N_OWNER_EMAIL"
echo "  API key: secrets/n8n_api_key"
